version: '3.1'
name: dna

services:

###########################################################################
############################### RTSP-SERVER ###############################
###########################################################################
  rtsp-server:
    container_name: 'rtsp-server'
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    environment:
      RTSP_PROTOCOLS: "tcp"

###########################################################################
################################ DNA_NODE #################################
###########################################################################
  dna-node:
    container_name: 'dna-node'
    image: kwlee0220/dna-node
    network_mode: host
    volumes:
      - ./dna.node:/dna.node
    environment:
      DNA_NODE_SYNC: "True"
      # DNA_NODE_SHOW: "True"
      DNA_NODE_SHOW_PROGRESS: "True"
      DISPLAY: "192.168.0.51:0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: dna_node --conf conf/dna.node.yaml
    depends_on:
      - rtsp-server
