id: etri:061

camera:
  uri: data/etri/etri_061.mp4
  size: [1920, 1080]
  sync: true
  threaded: false

tracker:
  uri: dna.tracker.dna_deepsort
  draw_zones: false
  # output: C:/Temp/data/track_output.csv

  dna_deepsort:
    # detector: dna.detect.yolov4
    detector: dna.detect.yolov5:model=m&score=0.45
    # detector: file:videos/etri/etri_061_det.txt
    min_detection_score: 0
    n_init: 5
    metric_threshold: 0.55
    max_iou_distance: 0.85
    max_overlap_ratio: 0.75
    max_age: 30
    min_size: [30, 20]
    det_mapping:
      car: car
      bus: car
      truck: car
    blind_zones:
      - [1309,223,1908,488]
      - [-3,634,387,1083]
      - [1741,508,1923,1087]
    dim_zones:
      - [996, 54, 1223, 328]
      - [734, 55, 1043, 312]
      - [-300, 512, 295, 997]

pipeline:
  min_path_length: 10
  attach_world_coordinates:
    camera_geometry: data/camera_geoms/etri_06.pickle

kafka_publisher:
  bootstrap_servers: [localhost:9092]
  topic: 'node-tracks'