version: '3.1'
name: dna-node

services:

###########################################################################
############################### RTSP-SERVER ###############################
###########################################################################
  rtsp-server:
    container_name: 'rtsp-server'
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    environment:
      RTSP_PROTOCOLS: "tcp"

###########################################################################
################################ DNA_NODE #################################
###########################################################################
  dna-node:
    container_name: 'dna-node'
    image: kwlee0220/dna-node
    network_mode: host
    volumes:
      - ./data/dna.node:/dna.node
      - ./data/torch_hub:/root/.cache/torch/hub
    environment:
      # DNA_NODE_CAMERA: "rtsp://admin:dnabased24@129.254.82.33:558/LiveChannel/3/media.smp"
      DNA_NODE_SYNC: "True"
      # DNA_NODE_SHOW: "True"
      # DNA_NODE_SHOW_PROGRESS: "True"
      DNA_NODE_FFMPEG_PATH: "/opt/conda/bin/ffmpeg"
      # DISPLAY: "192.168.0.15:0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: dna_node --conf conf/dna.node.yaml
    depends_on:
      - rtsp-server
